# Generated by Django 2.2 on 2023-07-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_employees', '0001_initial'),
        ('hr_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
                ('ot_rate', models.IntegerField(default=0, verbose_name='Ot Rate')),
                ('allowance', models.IntegerField(default=0, verbose_name='Allowance')),
                ('deduction', models.IntegerField(default=0, verbose_name='Deduction')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel')),
                ('tags', models.ManyToManyField(to='hr_tags.EmployeeTagModel')),
            ],
        ),
    ]
