# Generated by Django 2.2 on 2023-07-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_jobs', '0001_initial'),
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='department',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_jobs.JobModel'),
        ),
    ]
