# Generated by Django 2.2 on 2023-07-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0002_auto_20230716_1046'),
        ('hr_contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='department',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel'),
        ),
    ]
