# Generated by Django 2.2 on 2023-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_contracts', '0002_auto_20230716_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.ContractTagModel'),
        ),
    ]
