# Generated by Django 2.2 on 2023-07-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Name')),
                ('value', models.CharField(default='00,000.00', max_length=16)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cash_out', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel')),
                ('tags', models.ManyToManyField(to='hr_tags.EmployeeTagModel')),
            ],
        ),
    ]
